permalink: /:year/:month/:day/:title/

# 站点设置
title: "Moilk Blog"
email: MoilkNepho@gmail.com
description: "Moilk的个人博客"
keywords: "Moilk"

# 用户信息设置
weibo_username: Moilknepho
github_username: MoilkNepho

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: "/Base"
url: "http://127.0.0.1:4000"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
# duoshuo_shortname: 

# 百度统计设置
# baidu_analysis:
